# Generated by Django 3.1.3 on 2020-11-22 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_measurement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
