# Generated by Django 3.1.3 on 2020-12-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201122_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measured_value',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='gas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='localization',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='windows',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
