# Generated by Django 3.1.3 on 2020-12-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201206_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='alert',
            new_name='alarm',
        ),
    ]
