# Generated by Django 3.1.3 on 2020-12-07 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201206_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('dismissed', models.BooleanField(default=False)),
            ],
        ),
    ]
